//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R1, R3, L2, L5, L2, L1, R3, L4, R2, L2, L4, R2, L1, R1, L2, R3, L1, L4, R2, L5, R3, R4, L1, R2, L1, R3, L4, R5, L4, L5, R5, L3, R2, L3, L3, R1, R3, L4, R2, R5, L4, R1, L1, L1, R5, L2, R1, L2, R188, L5, L3, R5, R1, L2, L4, R3, R5, L3, R3, R45, L4, R4, R72, R2, R3, L1, R1, L1, L1, R192, L1, L1, L1, L4, R1, L2, L5, L3, R5, L3, R3, L4, L3, R1, R4, L2, R2, R3, L5, R3, L1, R1, R4, L2, L3, R1, R3, L4, L3, L4, L2, L2, R1, R3, L5, L1, R4, R2, L4, L1, R3, R3, R1, L5, L2, R4, R4, R2, R1, R5, R5, L4, L1, R5, R3, R4, R5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01_Input {
            get {
                return ResourceManager.GetString("Day01_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LRRLLLRDRURUDLRDDURULRULLDLRRLRLDULUDDDDLLRRLDUUDULDRURRLDULRRULDLRDUDLRLLLULDUURRRRURURULURRULRURDLULURDRDURDRLRRUUDRULLLLLDRULDDLLRDLURRLDUURDLRLUDLDUDLURLRLDRLUDUULRRRUUULLRDURUDRUDRDRLLDLDDDLDLRRULDUUDULRUDDRLLURDDRLDDUDLLLLULRDDUDDUUULRULUULRLLDULUDLLLLURRLDLUDLDDLDRLRRDRDUDDDLLLLLRRLLRLUDLULLDLDDRRUDDRLRDDURRDULLLURLRDLRRLRDLDURLDDULLLDRRURDULUDUDLLLDDDLLRLDDDLLRRLLURUULULDDDUDULUUURRUUDLDULULDRDDLURURDLDLULDUDUDDDDD
        ///RUURUDRDUULRDDLRLLLULLDDUDRDURDLRUULLLLUDUDRRUDUULRRUUDDURDDDLLLLRRUURULULLUDDLRDUDU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02_Input {
            get {
                return ResourceManager.GetString("Day02_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   541  588  421
        ///  827  272  126
        ///  660  514  367
        ///   39  703  839
        ///  229  871    3
        ///  237  956  841
        ///  898  566  112
        ///  101   79  112
        ///  813  541  146
        ///  603  135  565
        ///  335  363  180
        ///  382  493  669
        ///  545   81  843
        ///  657  960  849
        ///  823  909    9
        ///  370  194  908
        ///  101  750  317
        ///  295  671  968
        ///  656  431   64
        ///  634  291  245
        ///  819  663  266
        ///  504  662  829
        ///  760  590  918
        ///  733  859  258
        ///  197  651  137
        ///  357  799  638
        ///  544  250  597
        ///  604  654  431
        ///   90  870  184
        ///  609  535  604
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03_Input {
            get {
                return ResourceManager.GetString("Day03_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nzydfxpc-rclop-qwzhpc-qtylyntyr-769[oshgk]
        ///qzlozfhmf-bzmcx-bnzshmf-zbpthrhshnm-339[zmxdi]
        ///xtwtelcj-rclop-upwwjmply-zapcletzyd-743[itbds]
        ///mrxivrexmsrep-fewoix-ywiv-xiwxmrk-308[kzypw]
        ///ibghopzs-qobrm-difqvogwbu-142[lnrzo]
        ///irgyyolokj-xghhoz-lotgtiotm-228[vnmxd]
        ///foadouwbu-gqojsbusf-vibh-fsgsofqv-376[ymswi]
        ///jvuzbtly-nyhkl-wyvqljapsl-wshzapj-nyhzz-ylzlhyjo-903[jnyaz]
        ///amjmpdsj-cee-qcptgacq-236[caejm]
        ///nvrgfezqvu-avccpsvre-crsfirkfip-217[nrzcd]
        ///vdzonmhydc-bzmcx-bnzshmf-zbpthrhshnm-235[znyot]
        ///oxaflxzqfsb-mi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04_Input {
            get {
                return ResourceManager.GetString("Day04_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yksqurlc
        ///hangxyoi
        ///ikyfnszz
        ///lpucpqly
        ///mebitfkg
        ///txvynfxf
        ///qkjjkzlv
        ///zboxjpaz
        ///ijlepotw
        ///rhjolmth
        ///qphnlwok
        ///zhsuzvfc
        ///aqydciuw
        ///xywzachh
        ///jjfprial
        ///fqfigogj
        ///aglymzym
        ///varurjmr
        ///hziejnbj
        ///cuxmzuos
        ///fxlobgee
        ///dmgfztdp
        ///xdycegvz
        ///ovimnzwp
        ///uovtqmsr
        ///ukynvdub
        ///ifsxypxz
        ///bgiindmv
        ///aszamsyt
        ///qhqnxrgw
        ///sikzpkja
        ///adbjyzcm
        ///wegnenxz
        ///yaeqsqlb
        ///xssdsvdd
        ///hfadixdv
        ///xuxilufs
        ///zyulpexe
        ///eyhyrfxg
        ///gzouqych
        ///syswnzvb
        ///hfdfjeky
        ///eueretpq
        ///mawxsflw
        ///abmlttfz
        ///uudtrnrj
        ///hvchepau
        ///uvmmolck
        ///vghofgkt
        ///snxoobnv
        ///teihcctv
        ///ow [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day06_Input {
            get {
                return ResourceManager.GetString("Day06_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rhamaeovmbheijj[hkwbkqzlcscwjkyjulk]ajsxfuemamuqcjccbc
        ///gdlrknrmexvaypu[crqappbbcaplkkzb]vhvkjyadjsryysvj[nbvypeadikilcwg]jwxlimrgakadpxu[dgoanojvdvwfabtt]yqsalmulblolkgsheo
        ///dqpthtgufgzjojuvzvm[eejdhpcqyiydwod]iingwezvcbtowwzc[uzlxaqenhgsebqskn]wcucfmnlarrvdceuxqc[dkwcsxeitcobaylhbvc]klxammurpqgmpsxsr
        ///gmmfbtpprishiujnpdi[wedykxqyntvrkfdzom]uidgvubnregvorgnhm
        ///txxplravpgztjqcw[txgmmtlhmqpmmwp]bmhfgpmafxqwtrpr[inntmjmgqothdzfqgxq]cvtwvembpvdmcvk
        ///gkxjhpayoyrrpcr[mwyoahlkqyhtznyzrm]mvmurvsrgjunjjepn[mkoumuoh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day07_Input {
            get {
                return ResourceManager.GetString("Day07_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rect 1x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 5
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 2x1
        ///rotate row y=0 by 5
        ///rect 1x1
        ///rotate row y=0 by 5
        ///rect 4x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 5
        ///rect 4x1
        ///rotate row y=0 by 3
        ///rect 2x1
        ///rotate row y=0 by 5
        ///rect 4x1
        ///rotate row y=0 by 2
        ///rect 1x2
        ///rotate row y=1 by 6
        ///rotate row y=0 by 2
        ///rect 1x2
        ///rotate column x=32 by 1
        ///rotate column x=23 by 1
        ///rotate column x=13 by 1
        ///rot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day08_Input {
            get {
                return ResourceManager.GetString("Day08_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (106x9)(9x11)XRTHYQJRI(16x7)PQFHWDDUNODSQZFA(3x14)UTS(46x5)(11x2)ZPIAOZZMWEI(4x15)SDLK(12x10)BUQRPYWOFRHL(3x2)IUD(376x15)(56x2)(2x8)HN(8x6)EMTIYSST(29x14)UMUBTFMGRIFIJMVOFTRZJBYZKRZTR(72x7)(15x14)AIEJQAVGCXESYMW(33x11)BOGWCYAIJENVPIZOHXMHVSICYNVYYOYSQ(5x4)LNSRH(121x10)(35x11)ORVPLTOAYEYSFLWFTVMEKGERUMSXJEQGTWZ(3x10)NAG(10x11)OUJQJHTAYV(33x6)GHVYZOGPXXWXXWQOTKASZXBTKSWGYIDHJ(8x12)TXOGOMWU(31x13)(24x12)GKJSZHQTICHXVETPQMHLIKZD(62x12)(11x5)DAGFHJAOZEC(7x13)TLJQCQX(6x9)QEYKQQ(14x15)IBMGNTVYJNFYMG(6x2)WFGDKTVLSH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day09_Input {
            get {
                return ResourceManager.GetString("Day09_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bot 123 gives low to bot 191 and high to bot 162
        ///bot 191 gives low to output 9 and high to bot 192
        ///bot 182 gives low to bot 175 and high to bot 196
        ///bot 113 gives low to bot 172 and high to bot 94
        ///bot 78 gives low to bot 37 and high to bot 25
        ///bot 187 gives low to bot 125 and high to bot 45
        ///bot 71 gives low to bot 108 and high to bot 61
        ///bot 154 gives low to bot 2 and high to bot 64
        ///bot 142 gives low to bot 110 and high to bot 163
        ///bot 109 gives low to output 0 and high to bot 43
        ///bot 198 gives low to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10_Input {
            get {
                return ResourceManager.GetString("Day10_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first floor contains a polonium generator, a thulium generator, a thulium-compatible microchip, a promethium generator, a ruthenium generator, a ruthenium-compatible microchip, a cobalt generator, and a cobalt-compatible microchip.
        ///The second floor contains a polonium-compatible microchip and a promethium-compatible microchip.
        ///The third floor contains nothing relevant.
        ///The fourth floor contains nothing relevant.
        ///.
        /// </summary>
        internal static string Day11_Input {
            get {
                return ResourceManager.GetString("Day11_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first floor contains a hydrogen-compatible microchip and a lithium-compatible microchip.
        ///The second floor contains a hydrogen generator.
        ///The third floor contains a lithium generator.
        ///The fourth floor contains nothing relevant..
        /// </summary>
        internal static string Day11_TestInput {
            get {
                return ResourceManager.GetString("Day11_TestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cpy 1 a
        ///cpy 1 b
        ///cpy 26 d
        ///jnz c 2
        ///jnz 1 5
        ///cpy 7 c
        ///inc d
        ///dec c
        ///jnz c -2
        ///cpy a c
        ///inc a
        ///dec b
        ///jnz b -2
        ///cpy c b
        ///dec d
        ///jnz d -6
        ///cpy 14 c
        ///cpy 14 d
        ///inc a
        ///dec d
        ///jnz d -2
        ///dec c
        ///jnz c -5
        ///.
        /// </summary>
        internal static string Day12_Input {
            get {
                return ResourceManager.GetString("Day12_Input", resourceCulture);
            }
        }
    }
}
